version: "3.8"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
      - sse-server
    ports:
      - 7800:7800

  programming-api:
    build: programming-api
    image: programming-api
    restart: "on-failure"
    volumes:
      - ./programming-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env

  sse-server:
    build: sse-server
    image: sse-server
    restart: "on-failure"
    volumes:
      - ./sse-server/:/app
      - ./app-cache/:/app-cache
    expose:
      - 4000
    env_file:
      - project.env
    depends_on:
      - redis
      - database

  programming-ui:
    build: programming-ui
    image: programming-ui
    restart: "on-failure"
    volumes:
      - ./programming-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - programming-api
      - sse-server

  grader-api:
    build: grader-api
    image: grader-api
    restart: "on-failure"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000
    depends_on:
      - redis
    deploy:
      replicas: 2

  database:
    container_name: database-server-dab-p1-99f97847-4398-4a1b-b2e5-d211a33c1e01
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  playwright:
    entrypoint: "/bin/true"
    build: playwright
    network_mode: host
    depends_on:
      - nginx
    volumes: 
      - ./playwright/tests:/app/tests
  
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379